# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RCRwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 969)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cam_frame = QtWidgets.QFrame(self.centralwidget)
        self.cam_frame.setGeometry(QtCore.QRect(290, 10, 771, 491))
        self.cam_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.cam_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cam_frame.setObjectName("cam_frame")
        self.adjust_cam_base_gBox = QtWidgets.QGroupBox(self.cam_frame)
        self.adjust_cam_base_gBox.setGeometry(QtCore.QRect(10, 380, 761, 101))
        self.adjust_cam_base_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.adjust_cam_base_gBox.setObjectName("adjust_cam_base_gBox")
        self.cam_base_param_adjust_btn = QtWidgets.QPushButton(self.adjust_cam_base_gBox)
        self.cam_base_param_adjust_btn.setGeometry(QtCore.QRect(620, 30, 41, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_base_param_adjust_btn.setFont(font)
        self.cam_base_param_adjust_btn.setObjectName("cam_base_param_adjust_btn")
        self.layoutWidget = QtWidgets.QWidget(self.adjust_cam_base_gBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 461, 60))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pitch_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pitch_label.setFont(font)
        self.pitch_label.setObjectName("pitch_label")
        self.gridLayout_4.addWidget(self.pitch_label, 0, 0, 1, 1)
        self.cam_base_pitch_ledit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_base_pitch_ledit.setFont(font)
        self.cam_base_pitch_ledit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cam_base_pitch_ledit.setObjectName("cam_base_pitch_ledit")
        self.gridLayout_4.addWidget(self.cam_base_pitch_ledit, 0, 1, 1, 1)
        self.cam_base_pitch_hSlider = QtWidgets.QSlider(self.layoutWidget)
        self.cam_base_pitch_hSlider.setMaximum(100)
        self.cam_base_pitch_hSlider.setSliderPosition(20)
        self.cam_base_pitch_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cam_base_pitch_hSlider.setObjectName("cam_base_pitch_hSlider")
        self.gridLayout_4.addWidget(self.cam_base_pitch_hSlider, 0, 2, 1, 1)
        self.yaw_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yaw_label.setFont(font)
        self.yaw_label.setObjectName("yaw_label")
        self.gridLayout_4.addWidget(self.yaw_label, 1, 0, 1, 1)
        self.cam_base_yaw_ledit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_base_yaw_ledit.setFont(font)
        self.cam_base_yaw_ledit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cam_base_yaw_ledit.setObjectName("cam_base_yaw_ledit")
        self.gridLayout_4.addWidget(self.cam_base_yaw_ledit, 1, 1, 1, 1)
        self.cam_base_yaw_hSlider = QtWidgets.QSlider(self.layoutWidget)
        self.cam_base_yaw_hSlider.setMaximum(180)
        self.cam_base_yaw_hSlider.setSliderPosition(90)
        self.cam_base_yaw_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.cam_base_yaw_hSlider.setObjectName("cam_base_yaw_hSlider")
        self.gridLayout_4.addWidget(self.cam_base_yaw_hSlider, 1, 2, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(0, 1)
        self.gridLayout_4.setColumnMinimumWidth(1, 1)
        self.gridLayout_4.setColumnMinimumWidth(2, 4)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 4)
        self.layoutWidget1 = QtWidgets.QWidget(self.adjust_cam_base_gBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(470, 30, 82, 60))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cam_base_back_angle_btn = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_base_back_angle_btn.setFont(font)
        self.cam_base_back_angle_btn.setObjectName("cam_base_back_angle_btn")
        self.verticalLayout_6.addWidget(self.cam_base_back_angle_btn)
        self.cam_base_set_angle_btn = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_base_set_angle_btn.setFont(font)
        self.cam_base_set_angle_btn.setObjectName("cam_base_set_angle_btn")
        self.verticalLayout_6.addWidget(self.cam_base_set_angle_btn)
        self.cam_base_adjust_btn = QtWidgets.QPushButton(self.adjust_cam_base_gBox)
        self.cam_base_adjust_btn.setGeometry(QtCore.QRect(560, 30, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_base_adjust_btn.setFont(font)
        self.cam_base_adjust_btn.setObjectName("cam_base_adjust_btn")
        self.layoutWidget2 = QtWidgets.QWidget(self.adjust_cam_base_gBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(670, 30, 92, 60))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pitch_label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pitch_label_2.setFont(font)
        self.pitch_label_2.setObjectName("pitch_label_2")
        self.gridLayout_7.addWidget(self.pitch_label_2, 0, 0, 1, 1)
        self.cam_processing_len_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_processing_len_edit.setFont(font)
        self.cam_processing_len_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cam_processing_len_edit.setObjectName("cam_processing_len_edit")
        self.gridLayout_7.addWidget(self.cam_processing_len_edit, 0, 1, 1, 1)
        self.pitch_label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pitch_label_3.setFont(font)
        self.pitch_label_3.setObjectName("pitch_label_3")
        self.gridLayout_7.addWidget(self.pitch_label_3, 1, 0, 1, 1)
        self.cam_processing_width_edit = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam_processing_width_edit.setFont(font)
        self.cam_processing_width_edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cam_processing_width_edit.setObjectName("cam_processing_width_edit")
        self.gridLayout_7.addWidget(self.cam_processing_width_edit, 1, 1, 1, 1)
        self.base_cam_gBox = QtWidgets.QGroupBox(self.cam_frame)
        self.base_cam_gBox.setGeometry(QtCore.QRect(11, 0, 362, 379))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.base_cam_gBox.setFont(font)
        self.base_cam_gBox.setObjectName("base_cam_gBox")
        self.layoutWidget_3 = QtWidgets.QWidget(self.base_cam_gBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 30, 361, 341))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cam_base_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.cam_base_label.setObjectName("cam_base_label")
        self.verticalLayout.addWidget(self.cam_base_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.com_cam_base_box = QtWidgets.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.com_cam_base_box.setFont(font)
        self.com_cam_base_box.setObjectName("com_cam_base_box")
        self.com_cam_base_box.addItem("")
        self.com_cam_base_box.addItem("")
        self.com_cam_base_box.addItem("")
        self.horizontalLayout.addWidget(self.com_cam_base_box)
        self.open_cam_base_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.open_cam_base_btn.setFont(font)
        self.open_cam_base_btn.setObjectName("open_cam_base_btn")
        self.horizontalLayout.addWidget(self.open_cam_base_btn)
        self.close_cam_base_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.close_cam_base_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.close_cam_base_btn.setFont(font)
        self.close_cam_base_btn.setCheckable(False)
        self.close_cam_base_btn.setDefault(False)
        self.close_cam_base_btn.setObjectName("close_cam_base_btn")
        self.horizontalLayout.addWidget(self.close_cam_base_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.head_cam_gBox = QtWidgets.QGroupBox(self.cam_frame)
        self.head_cam_gBox.setGeometry(QtCore.QRect(379, 1, 391, 379))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.head_cam_gBox.setFont(font)
        self.head_cam_gBox.setObjectName("head_cam_gBox")
        self.layoutWidget_4 = QtWidgets.QWidget(self.head_cam_gBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 30, 381, 341))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cam_head_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.cam_head_label.setObjectName("cam_head_label")
        self.verticalLayout_2.addWidget(self.cam_head_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.com_cam_head_box = QtWidgets.QComboBox(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.com_cam_head_box.setFont(font)
        self.com_cam_head_box.setObjectName("com_cam_head_box")
        self.com_cam_head_box.addItem("")
        self.com_cam_head_box.addItem("")
        self.com_cam_head_box.addItem("")
        self.horizontalLayout_2.addWidget(self.com_cam_head_box)
        self.open_cam_head_btn = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.open_cam_head_btn.setFont(font)
        self.open_cam_head_btn.setObjectName("open_cam_head_btn")
        self.horizontalLayout_2.addWidget(self.open_cam_head_btn)
        self.close_cam_head_btn = QtWidgets.QPushButton(self.layoutWidget_4)
        self.close_cam_head_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.close_cam_head_btn.setFont(font)
        self.close_cam_head_btn.setCheckable(False)
        self.close_cam_head_btn.setDefault(False)
        self.close_cam_head_btn.setObjectName("close_cam_head_btn")
        self.horizontalLayout_2.addWidget(self.close_cam_head_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.controller_frame = QtWidgets.QFrame(self.centralwidget)
        self.controller_frame.setGeometry(QtCore.QRect(290, 510, 771, 401))
        self.controller_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controller_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controller_frame.setObjectName("controller_frame")
        self.clean_panel_gBox = QtWidgets.QGroupBox(self.controller_frame)
        self.clean_panel_gBox.setGeometry(QtCore.QRect(10, 0, 371, 351))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.clean_panel_gBox.setFont(font)
        self.clean_panel_gBox.setObjectName("clean_panel_gBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.clean_panel_gBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 40, 371, 301))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cleaning_ops_gBox = QtWidgets.QGroupBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cleaning_ops_gBox.setFont(font)
        self.cleaning_ops_gBox.setObjectName("cleaning_ops_gBox")
        self.start_clean_ops_btn = QtWidgets.QPushButton(self.cleaning_ops_gBox)
        self.start_clean_ops_btn.setGeometry(QtCore.QRect(20, 30, 141, 26))
        self.start_clean_ops_btn.setObjectName("start_clean_ops_btn")
        self.stop_clean_ops_btn = QtWidgets.QPushButton(self.cleaning_ops_gBox)
        self.stop_clean_ops_btn.setGeometry(QtCore.QRect(200, 30, 131, 26))
        self.stop_clean_ops_btn.setObjectName("stop_clean_ops_btn")
        self.verticalLayout_3.addWidget(self.cleaning_ops_gBox)
        self.wate_pump_gBox = QtWidgets.QGroupBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wate_pump_gBox.setFont(font)
        self.wate_pump_gBox.setObjectName("wate_pump_gBox")
        self.open_water_pump_btn = QtWidgets.QPushButton(self.wate_pump_gBox)
        self.open_water_pump_btn.setGeometry(QtCore.QRect(20, 30, 141, 26))
        self.open_water_pump_btn.setObjectName("open_water_pump_btn")
        self.close_water_pump_btn = QtWidgets.QPushButton(self.wate_pump_gBox)
        self.close_water_pump_btn.setGeometry(QtCore.QRect(200, 30, 131, 26))
        self.close_water_pump_btn.setObjectName("close_water_pump_btn")
        self.verticalLayout_3.addWidget(self.wate_pump_gBox)
        self.sewage_pump_gBox = QtWidgets.QGroupBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sewage_pump_gBox.setFont(font)
        self.sewage_pump_gBox.setObjectName("sewage_pump_gBox")
        self.open_sewage_pump_btn = QtWidgets.QPushButton(self.sewage_pump_gBox)
        self.open_sewage_pump_btn.setGeometry(QtCore.QRect(20, 30, 141, 26))
        self.open_sewage_pump_btn.setObjectName("open_sewage_pump_btn")
        self.close_sewage_pump_btn = QtWidgets.QPushButton(self.sewage_pump_gBox)
        self.close_sewage_pump_btn.setGeometry(QtCore.QRect(200, 30, 131, 26))
        self.close_sewage_pump_btn.setObjectName("close_sewage_pump_btn")
        self.verticalLayout_3.addWidget(self.sewage_pump_gBox)
        self.ur_ops_gBox = QtWidgets.QGroupBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ur_ops_gBox.setFont(font)
        self.ur_ops_gBox.setObjectName("ur_ops_gBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.ur_ops_gBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 30, 340, 28))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.unit_touch_window_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.unit_touch_window_btn.setObjectName("unit_touch_window_btn")
        self.horizontalLayout_7.addWidget(self.unit_touch_window_btn)
        self.unit_back_init_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.unit_back_init_btn.setObjectName("unit_back_init_btn")
        self.horizontalLayout_7.addWidget(self.unit_back_init_btn)
        self.unit_auto_clean_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.unit_auto_clean_btn.setObjectName("unit_auto_clean_btn")
        self.horizontalLayout_7.addWidget(self.unit_auto_clean_btn)
        self.unit_stop_btn = QtWidgets.QPushButton(self.layoutWidget4)
        self.unit_stop_btn.setObjectName("unit_stop_btn")
        self.horizontalLayout_7.addWidget(self.unit_stop_btn)
        self.verticalLayout_3.addWidget(self.ur_ops_gBox)
        self.rcr_panel_gBox = QtWidgets.QGroupBox(self.controller_frame)
        self.rcr_panel_gBox.setGeometry(QtCore.QRect(390, 0, 371, 351))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rcr_panel_gBox.setFont(font)
        self.rcr_panel_gBox.setObjectName("rcr_panel_gBox")
        self.rcr_info_textEdit = QtWidgets.QTextEdit(self.rcr_panel_gBox)
        self.rcr_info_textEdit.setGeometry(QtCore.QRect(10, 180, 351, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rcr_info_textEdit.setFont(font)
        self.rcr_info_textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rcr_info_textEdit.setObjectName("rcr_info_textEdit")
        self.layoutWidget5 = QtWidgets.QWidget(self.rcr_panel_gBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 110, 351, 28))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.step_up_rcr_btn = QtWidgets.QPushButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.step_up_rcr_btn.setFont(font)
        self.step_up_rcr_btn.setObjectName("step_up_rcr_btn")
        self.horizontalLayout_13.addWidget(self.step_up_rcr_btn)
        self.step_down_rcr_btn = QtWidgets.QPushButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.step_down_rcr_btn.setFont(font)
        self.step_down_rcr_btn.setObjectName("step_down_rcr_btn")
        self.horizontalLayout_13.addWidget(self.step_down_rcr_btn)
        self.up_rcr_btn = QtWidgets.QPushButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.up_rcr_btn.setFont(font)
        self.up_rcr_btn.setObjectName("up_rcr_btn")
        self.horizontalLayout_13.addWidget(self.up_rcr_btn)
        self.down_rcr_btn = QtWidgets.QPushButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.down_rcr_btn.setFont(font)
        self.down_rcr_btn.setObjectName("down_rcr_btn")
        self.horizontalLayout_13.addWidget(self.down_rcr_btn)
        self.layoutWidget6 = QtWidgets.QWidget(self.rcr_panel_gBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 140, 338, 30))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clear_rcr_txt_btn = QtWidgets.QPushButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_rcr_txt_btn.setFont(font)
        self.clear_rcr_txt_btn.setObjectName("clear_rcr_txt_btn")
        self.horizontalLayout_3.addWidget(self.clear_rcr_txt_btn)
        self.stop_rcr_btn = QtWidgets.QPushButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.stop_rcr_btn.setFont(font)
        self.stop_rcr_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.stop_rcr_btn.setObjectName("stop_rcr_btn")
        self.horizontalLayout_3.addWidget(self.stop_rcr_btn)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 4)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_14.setStretch(0, 4)
        self.layoutWidget7 = QtWidgets.QWidget(self.rcr_panel_gBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 40, 339, 61))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.speed_rcr_lineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.speed_rcr_lineEdit.setFont(font)
        self.speed_rcr_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.speed_rcr_lineEdit.setObjectName("speed_rcr_lineEdit")
        self.gridLayout_3.addWidget(self.speed_rcr_lineEdit, 0, 1, 1, 1)
        self.height_set_rcr_lineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.height_set_rcr_lineEdit.setFont(font)
        self.height_set_rcr_lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.height_set_rcr_lineEdit.setObjectName("height_set_rcr_lineEdit")
        self.gridLayout_3.addWidget(self.height_set_rcr_lineEdit, 3, 3, 1, 1)
        self.rcr_ab_height_label = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rcr_ab_height_label.setFont(font)
        self.rcr_ab_height_label.setObjectName("rcr_ab_height_label")
        self.gridLayout_3.addWidget(self.rcr_ab_height_label, 3, 2, 1, 1)
        self.rcr_ab_vel_label = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rcr_ab_vel_label.setFont(font)
        self.rcr_ab_vel_label.setObjectName("rcr_ab_vel_label")
        self.gridLayout_3.addWidget(self.rcr_ab_vel_label, 0, 2, 1, 1)
        self.height_rcr_lineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.height_rcr_lineEdit.setFont(font)
        self.height_rcr_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.height_rcr_lineEdit.setObjectName("height_rcr_lineEdit")
        self.gridLayout_3.addWidget(self.height_rcr_lineEdit, 3, 1, 1, 1)
        self.vel_set_rcr_lineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vel_set_rcr_lineEdit.setFont(font)
        self.vel_set_rcr_lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.vel_set_rcr_lineEdit.setObjectName("vel_set_rcr_lineEdit")
        self.gridLayout_3.addWidget(self.vel_set_rcr_lineEdit, 0, 3, 1, 1)
        self.rcr_speed_label = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.rcr_speed_label.setFont(font)
        self.rcr_speed_label.setObjectName("rcr_speed_label")
        self.gridLayout_3.addWidget(self.rcr_speed_label, 0, 0, 1, 1)
        self.rcr_height_label = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rcr_height_label.setFont(font)
        self.rcr_height_label.setObjectName("rcr_height_label")
        self.gridLayout_3.addWidget(self.rcr_height_label, 3, 0, 1, 1)
        self.rcr_ab_vel_label_2 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rcr_ab_vel_label_2.setFont(font)
        self.rcr_ab_vel_label_2.setObjectName("rcr_ab_vel_label_2")
        self.gridLayout_3.addWidget(self.rcr_ab_vel_label_2, 0, 4, 1, 1)
        self.rcr_ab_height_label_2 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rcr_ab_height_label_2.setFont(font)
        self.rcr_ab_height_label_2.setObjectName("rcr_ab_height_label_2")
        self.gridLayout_3.addWidget(self.rcr_ab_height_label_2, 3, 4, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.motor_arduino_ctr_label = QtWidgets.QLabel(self.controller_frame)
        self.motor_arduino_ctr_label.setGeometry(QtCore.QRect(10, 370, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.motor_arduino_ctr_label.setFont(font)
        self.motor_arduino_ctr_label.setObjectName("motor_arduino_ctr_label")
        self.layoutWidget8 = QtWidgets.QWidget(self.controller_frame)
        self.layoutWidget8.setGeometry(QtCore.QRect(160, 360, 461, 29))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.detect_control_com_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.detect_control_com_btn.setObjectName("detect_control_com_btn")
        self.horizontalLayout_4.addWidget(self.detect_control_com_btn)
        self.com_control_box = QtWidgets.QComboBox(self.layoutWidget8)
        self.com_control_box.setObjectName("com_control_box")
        self.horizontalLayout_4.addWidget(self.com_control_box)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.open_control_com_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.open_control_com_btn.setEnabled(False)
        self.open_control_com_btn.setObjectName("open_control_com_btn")
        self.horizontalLayout_5.addWidget(self.open_control_com_btn)
        self.close_control_com_btn = QtWidgets.QPushButton(self.layoutWidget8)
        self.close_control_com_btn.setEnabled(False)
        self.close_control_com_btn.setAutoDefault(False)
        self.close_control_com_btn.setDefault(False)
        self.close_control_com_btn.setObjectName("close_control_com_btn")
        self.horizontalLayout_5.addWidget(self.close_control_com_btn)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 1)
        self.rcrnode_open_btn = QtWidgets.QPushButton(self.controller_frame)
        self.rcrnode_open_btn.setGeometry(QtCore.QRect(630, 360, 121, 26))
        self.rcrnode_open_btn.setObjectName("rcrnode_open_btn")
        self.icon_frame = QtWidgets.QFrame(self.centralwidget)
        self.icon_frame.setGeometry(QtCore.QRect(20, 10, 261, 131))
        self.icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.icon_frame.setObjectName("icon_frame")
        self.layoutWidget9 = QtWidgets.QWidget(self.icon_frame)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 10, 241, 111))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.icon_cuhk_label = QtWidgets.QLabel(self.layoutWidget9)
        self.icon_cuhk_label.setObjectName("icon_cuhk_label")
        self.horizontalLayout_9.addWidget(self.icon_cuhk_label)
        self.icon_curi_label = QtWidgets.QLabel(self.layoutWidget9)
        self.icon_curi_label.setObjectName("icon_curi_label")
        self.horizontalLayout_9.addWidget(self.icon_curi_label)
        self.real_time_info_frame = QtWidgets.QFrame(self.centralwidget)
        self.real_time_info_frame.setGeometry(QtCore.QRect(20, 150, 261, 351))
        self.real_time_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.real_time_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.real_time_info_frame.setObjectName("real_time_info_frame")
        self.real_time_info_label = QtWidgets.QLabel(self.real_time_info_frame)
        self.real_time_info_label.setGeometry(QtCore.QRect(10, 10, 211, 18))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.real_time_info_label.setFont(font)
        self.real_time_info_label.setObjectName("real_time_info_label")
        self.real_time_info_textEdit = QtWidgets.QTextEdit(self.real_time_info_frame)
        self.real_time_info_textEdit.setGeometry(QtCore.QRect(0, 40, 261, 271))
        self.real_time_info_textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.real_time_info_textEdit.setObjectName("real_time_info_textEdit")
        self.clear_real_time_txt_btn = QtWidgets.QPushButton(self.real_time_info_frame)
        self.clear_real_time_txt_btn.setGeometry(QtCore.QRect(50, 320, 161, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_real_time_txt_btn.setFont(font)
        self.clear_real_time_txt_btn.setObjectName("clear_real_time_txt_btn")
        self.sensor_frame = QtWidgets.QFrame(self.centralwidget)
        self.sensor_frame.setGeometry(QtCore.QRect(20, 510, 261, 401))
        self.sensor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor_frame.setObjectName("sensor_frame")
        self.sensor_info_gBox = QtWidgets.QGroupBox(self.sensor_frame)
        self.sensor_info_gBox.setGeometry(QtCore.QRect(0, 0, 261, 321))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sensor_info_gBox.setFont(font)
        self.sensor_info_gBox.setObjectName("sensor_info_gBox")
        self.clear_sensor_txt_btn = QtWidgets.QPushButton(self.sensor_info_gBox)
        self.clear_sensor_txt_btn.setGeometry(QtCore.QRect(160, 100, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_sensor_txt_btn.setFont(font)
        self.clear_sensor_txt_btn.setObjectName("clear_sensor_txt_btn")
        self.sensor_info_textEdit = QtWidgets.QTextEdit(self.sensor_info_gBox)
        self.sensor_info_textEdit.setGeometry(QtCore.QRect(10, 150, 241, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sensor_info_textEdit.setFont(font)
        self.sensor_info_textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sensor_info_textEdit.setObjectName("sensor_info_textEdit")
        self.layoutWidget10 = QtWidgets.QWidget(self.sensor_info_gBox)
        self.layoutWidget10.setGeometry(QtCore.QRect(10, 90, 131, 52))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget10)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sensor_N_lab = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_N_lab.setFont(font)
        self.sensor_N_lab.setObjectName("sensor_N_lab")
        self.gridLayout_5.addWidget(self.sensor_N_lab, 1, 1, 1, 1)
        self.force_lineEdit = QtWidgets.QLineEdit(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.force_lineEdit.setFont(font)
        self.force_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.force_lineEdit.setObjectName("force_lineEdit")
        self.gridLayout_5.addWidget(self.force_lineEdit, 1, 0, 1, 1)
        self.sensor_force_label = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_force_label.setFont(font)
        self.sensor_force_label.setObjectName("sensor_force_label")
        self.gridLayout_5.addWidget(self.sensor_force_label, 0, 0, 1, 2)
        self.layoutWidget11 = QtWidgets.QWidget(self.sensor_info_gBox)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 40, 207, 52))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget11)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sensor_sonic_label = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_sonic_label.setFont(font)
        self.sensor_sonic_label.setObjectName("sensor_sonic_label")
        self.gridLayout_6.addWidget(self.sensor_sonic_label, 0, 0, 1, 2)
        self.sonic_lineEdit = QtWidgets.QLineEdit(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sonic_lineEdit.setFont(font)
        self.sonic_lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sonic_lineEdit.setObjectName("sonic_lineEdit")
        self.gridLayout_6.addWidget(self.sonic_lineEdit, 1, 0, 1, 1)
        self.sensor_cm_label = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensor_cm_label.setFont(font)
        self.sensor_cm_label.setObjectName("sensor_cm_label")
        self.gridLayout_6.addWidget(self.sensor_cm_label, 1, 1, 1, 1)
        self.layoutWidget12 = QtWidgets.QWidget(self.sensor_frame)
        self.layoutWidget12.setGeometry(QtCore.QRect(11, 330, 231, 28))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.detect_sensor_com_btn = QtWidgets.QPushButton(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.detect_sensor_com_btn.setFont(font)
        self.detect_sensor_com_btn.setObjectName("detect_sensor_com_btn")
        self.horizontalLayout_11.addWidget(self.detect_sensor_com_btn)
        self.com_sensor_box = QtWidgets.QComboBox(self.layoutWidget12)
        self.com_sensor_box.setObjectName("com_sensor_box")
        self.horizontalLayout_11.addWidget(self.com_sensor_box)
        self.horizontalLayout_11.setStretch(0, 2)
        self.horizontalLayout_11.setStretch(1, 4)
        self.layoutWidget13 = QtWidgets.QWidget(self.sensor_frame)
        self.layoutWidget13.setGeometry(QtCore.QRect(11, 360, 231, 28))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.open_sensor_com_btn = QtWidgets.QPushButton(self.layoutWidget13)
        self.open_sensor_com_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.open_sensor_com_btn.setFont(font)
        self.open_sensor_com_btn.setObjectName("open_sensor_com_btn")
        self.horizontalLayout_12.addWidget(self.open_sensor_com_btn)
        self.close_sensor_com_btn = QtWidgets.QPushButton(self.layoutWidget13)
        self.close_sensor_com_btn.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.close_sensor_com_btn.setFont(font)
        self.close_sensor_com_btn.setAutoDefault(False)
        self.close_sensor_com_btn.setDefault(False)
        self.close_sensor_com_btn.setObjectName("close_sensor_com_btn")
        self.horizontalLayout_12.addWidget(self.close_sensor_com_btn)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1070, 10, 301, 901))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 281, 471))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.ur_info_textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.ur_info_textEdit.setGeometry(QtCore.QRect(0, 30, 281, 441))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ur_info_textEdit.setFont(font)
        self.ur_info_textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ur_info_textEdit.setObjectName("ur_info_textEdit")
        self.adjust_UR_EE_pos_gBox = QtWidgets.QGroupBox(self.frame)
        self.adjust_UR_EE_pos_gBox.setGeometry(QtCore.QRect(10, 590, 261, 91))
        self.adjust_UR_EE_pos_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.adjust_UR_EE_pos_gBox.setObjectName("adjust_UR_EE_pos_gBox")
        self.layoutWidget14 = QtWidgets.QWidget(self.adjust_UR_EE_pos_gBox)
        self.layoutWidget14.setGeometry(QtCore.QRect(3, 19, 254, 71))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget14)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ur_forward_btn = QtWidgets.QPushButton(self.layoutWidget14)
        self.ur_forward_btn.setEnabled(False)
        self.ur_forward_btn.setObjectName("ur_forward_btn")
        self.gridLayout.addWidget(self.ur_forward_btn, 0, 0, 1, 1)
        self.ur_left_btn = QtWidgets.QPushButton(self.layoutWidget14)
        self.ur_left_btn.setEnabled(False)
        self.ur_left_btn.setObjectName("ur_left_btn")
        self.gridLayout.addWidget(self.ur_left_btn, 0, 1, 1, 1)
        self.ur_up_btn = QtWidgets.QPushButton(self.layoutWidget14)
        self.ur_up_btn.setEnabled(False)
        self.ur_up_btn.setObjectName("ur_up_btn")
        self.gridLayout.addWidget(self.ur_up_btn, 0, 2, 1, 1)
        self.ur_back_btn = QtWidgets.QPushButton(self.layoutWidget14)
        self.ur_back_btn.setEnabled(False)
        self.ur_back_btn.setObjectName("ur_back_btn")
        self.gridLayout.addWidget(self.ur_back_btn, 1, 0, 1, 1)
        self.ur_right_btn = QtWidgets.QPushButton(self.layoutWidget14)
        self.ur_right_btn.setEnabled(False)
        self.ur_right_btn.setObjectName("ur_right_btn")
        self.gridLayout.addWidget(self.ur_right_btn, 1, 1, 1, 1)
        self.ur_down_btn = QtWidgets.QPushButton(self.layoutWidget14)
        self.ur_down_btn.setEnabled(False)
        self.ur_down_btn.setObjectName("ur_down_btn")
        self.gridLayout.addWidget(self.ur_down_btn, 1, 2, 1, 1)
        self.adjust_UR_EE_atti_gBox = QtWidgets.QGroupBox(self.frame)
        self.adjust_UR_EE_atti_gBox.setGeometry(QtCore.QRect(10, 690, 271, 91))
        self.adjust_UR_EE_atti_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.adjust_UR_EE_atti_gBox.setObjectName("adjust_UR_EE_atti_gBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.adjust_UR_EE_atti_gBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 254, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ur_ee_roll1_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_ee_roll1_btn.setEnabled(False)
        self.ur_ee_roll1_btn.setObjectName("ur_ee_roll1_btn")
        self.gridLayout_2.addWidget(self.ur_ee_roll1_btn, 0, 0, 1, 1)
        self.ur_ee_pitch1_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_ee_pitch1_btn.setEnabled(False)
        self.ur_ee_pitch1_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ur_ee_pitch1_btn.setObjectName("ur_ee_pitch1_btn")
        self.gridLayout_2.addWidget(self.ur_ee_pitch1_btn, 0, 1, 1, 1)
        self.ur_ee_roll2_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_ee_roll2_btn.setEnabled(False)
        self.ur_ee_roll2_btn.setObjectName("ur_ee_roll2_btn")
        self.gridLayout_2.addWidget(self.ur_ee_roll2_btn, 0, 2, 1, 1)
        self.ur_ee_yaw1_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_ee_yaw1_btn.setEnabled(False)
        self.ur_ee_yaw1_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ur_ee_yaw1_btn.setObjectName("ur_ee_yaw1_btn")
        self.gridLayout_2.addWidget(self.ur_ee_yaw1_btn, 1, 0, 1, 1)
        self.ur_ee_pitch2_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_ee_pitch2_btn.setEnabled(False)
        self.ur_ee_pitch2_btn.setObjectName("ur_ee_pitch2_btn")
        self.gridLayout_2.addWidget(self.ur_ee_pitch2_btn, 1, 1, 1, 1)
        self.ur_ee_yaw2_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_ee_yaw2_btn.setEnabled(False)
        self.ur_ee_yaw2_btn.setObjectName("ur_ee_yaw2_btn")
        self.gridLayout_2.addWidget(self.ur_ee_yaw2_btn, 1, 2, 1, 1)
        self.layoutWidget15 = QtWidgets.QWidget(self.frame)
        self.layoutWidget15.setGeometry(QtCore.QRect(30, 790, 221, 58))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget15)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.get_init_ur_pos_btn = QtWidgets.QPushButton(self.layoutWidget15)
        self.get_init_ur_pos_btn.setObjectName("get_init_ur_pos_btn")
        self.verticalLayout_4.addWidget(self.get_init_ur_pos_btn)
        self.get_final_ur_pos_btn = QtWidgets.QPushButton(self.layoutWidget15)
        self.get_final_ur_pos_btn.setObjectName("get_final_ur_pos_btn")
        self.verticalLayout_4.addWidget(self.get_final_ur_pos_btn)
        self.clear_ur_info_txt_btn = QtWidgets.QPushButton(self.frame)
        self.clear_ur_info_txt_btn.setGeometry(QtCore.QRect(70, 860, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_ur_info_txt_btn.setFont(font)
        self.clear_ur_info_txt_btn.setObjectName("clear_ur_info_txt_btn")
        self.layoutWidget16 = QtWidgets.QWidget(self.frame)
        self.layoutWidget16.setGeometry(QtCore.QRect(30, 480, 241, 104))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget16)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ur_choose_box = QtWidgets.QComboBox(self.layoutWidget16)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ur_choose_box.setFont(font)
        self.ur_choose_box.setObjectName("ur_choose_box")
        self.ur_choose_box.addItem("")
        self.ur_choose_box.addItem("")
        self.gridLayout_8.addWidget(self.ur_choose_box, 0, 0, 1, 1)
        self.ur_choose_ok_btn = QtWidgets.QPushButton(self.layoutWidget16)
        self.ur_choose_ok_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ur_choose_ok_btn.setFont(font)
        self.ur_choose_ok_btn.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 14pt \"Ubuntu\";")
        self.ur_choose_ok_btn.setObjectName("ur_choose_ok_btn")
        self.gridLayout_8.addWidget(self.ur_choose_ok_btn, 0, 1, 1, 1)
        self.ur_launch_btn = QtWidgets.QPushButton(self.layoutWidget16)
        self.ur_launch_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ur_launch_btn.setFont(font)
        self.ur_launch_btn.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 14pt \"Ubuntu\";")
        self.ur_launch_btn.setObjectName("ur_launch_btn")
        self.gridLayout_8.addWidget(self.ur_launch_btn, 1, 0, 1, 1)
        self.ur_close_launch_btn = QtWidgets.QPushButton(self.layoutWidget16)
        self.ur_close_launch_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ur_close_launch_btn.setFont(font)
        self.ur_close_launch_btn.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 14pt \"Ubuntu\";")
        self.ur_close_launch_btn.setObjectName("ur_close_launch_btn")
        self.gridLayout_8.addWidget(self.ur_close_launch_btn, 1, 1, 1, 1)
        self.ur_core_btn = QtWidgets.QPushButton(self.layoutWidget16)
        self.ur_core_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ur_core_btn.setFont(font)
        self.ur_core_btn.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 14pt \"Ubuntu\";")
        self.ur_core_btn.setObjectName("ur_core_btn")
        self.gridLayout_8.addWidget(self.ur_core_btn, 2, 0, 1, 1)
        self.ur_close_core_btn = QtWidgets.QPushButton(self.layoutWidget16)
        self.ur_close_core_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ur_close_core_btn.setFont(font)
        self.ur_close_core_btn.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 14pt \"Ubuntu\";")
        self.ur_close_core_btn.setObjectName("ur_close_core_btn")
        self.gridLayout_8.addWidget(self.ur_close_core_btn, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adjust_cam_base_gBox.setTitle(_translate("MainWindow", "Base Camera Pos Adjustment"))
        self.cam_base_param_adjust_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>cam angle adjust button</p></body></html>"))
        self.cam_base_param_adjust_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>set in base cam LSD detection params</p></body></html>"))
        self.cam_base_param_adjust_btn.setText(_translate("MainWindow", "SET"))
        self.pitch_label.setText(_translate("MainWindow", "pitch(1)"))
        self.cam_base_pitch_ledit.setText(_translate("MainWindow", "120"))
        self.cam_base_pitch_ledit.setPlaceholderText(_translate("MainWindow", "100"))
        self.yaw_label.setText(_translate("MainWindow", "yaw(2)"))
        self.cam_base_yaw_ledit.setText(_translate("MainWindow", "140"))
        self.cam_base_yaw_ledit.setPlaceholderText(_translate("MainWindow", "50"))
        self.cam_base_back_angle_btn.setText(_translate("MainWindow", "back init"))
        self.cam_base_set_angle_btn.setText(_translate("MainWindow", "set init"))
        self.cam_base_adjust_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>cam angle adjust button</p></body></html>"))
        self.cam_base_adjust_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>set servomotor angles</p></body></html>"))
        self.cam_base_adjust_btn.setText(_translate("MainWindow", "OK "))
        self.pitch_label_2.setText(_translate("MainWindow", "len"))
        self.cam_processing_len_edit.setText(_translate("MainWindow", "400"))
        self.cam_processing_len_edit.setPlaceholderText(_translate("MainWindow", "100"))
        self.pitch_label_3.setText(_translate("MainWindow", "wid"))
        self.cam_processing_width_edit.setText(_translate("MainWindow", "5.0"))
        self.cam_processing_width_edit.setPlaceholderText(_translate("MainWindow", "100"))
        self.base_cam_gBox.setTitle(_translate("MainWindow", "Base camera"))
        self.cam_base_label.setText(_translate("MainWindow", "base"))
        self.com_cam_base_box.setItemText(0, _translate("MainWindow", "video0"))
        self.com_cam_base_box.setItemText(1, _translate("MainWindow", "video1"))
        self.com_cam_base_box.setItemText(2, _translate("MainWindow", "video2"))
        self.open_cam_base_btn.setText(_translate("MainWindow", "open"))
        self.close_cam_base_btn.setText(_translate("MainWindow", "close"))
        self.head_cam_gBox.setTitle(_translate("MainWindow", "Head camera"))
        self.cam_head_label.setText(_translate("MainWindow", "head"))
        self.com_cam_head_box.setItemText(0, _translate("MainWindow", "video1"))
        self.com_cam_head_box.setItemText(1, _translate("MainWindow", "video2"))
        self.com_cam_head_box.setItemText(2, _translate("MainWindow", "video0"))
        self.open_cam_head_btn.setText(_translate("MainWindow", "open"))
        self.close_cam_head_btn.setText(_translate("MainWindow", "close"))
        self.clean_panel_gBox.setTitle(_translate("MainWindow", "Cleaning Panel"))
        self.cleaning_ops_gBox.setTitle(_translate("MainWindow", "Cleaning Ops"))
        self.start_clean_ops_btn.setText(_translate("MainWindow", "Start"))
        self.stop_clean_ops_btn.setText(_translate("MainWindow", "Stop"))
        self.wate_pump_gBox.setTitle(_translate("MainWindow", "Water Pump"))
        self.open_water_pump_btn.setText(_translate("MainWindow", "Open"))
        self.close_water_pump_btn.setText(_translate("MainWindow", "Close"))
        self.sewage_pump_gBox.setTitle(_translate("MainWindow", "Sewage Pump"))
        self.open_sewage_pump_btn.setText(_translate("MainWindow", "Open"))
        self.close_sewage_pump_btn.setText(_translate("MainWindow", "Close"))
        self.ur_ops_gBox.setTitle(_translate("MainWindow", "Cleaning Unit to Window"))
        self.unit_touch_window_btn.setText(_translate("MainWindow", "Touch"))
        self.unit_back_init_btn.setText(_translate("MainWindow", "Back"))
        self.unit_auto_clean_btn.setText(_translate("MainWindow", "Auto"))
        self.unit_stop_btn.setText(_translate("MainWindow", "Stop"))
        self.rcr_panel_gBox.setTitle(_translate("MainWindow", "  Rope Climbing Robot Panel"))
        self.step_up_rcr_btn.setText(_translate("MainWindow", "stepUP"))
        self.step_down_rcr_btn.setText(_translate("MainWindow", "stepDOWN"))
        self.up_rcr_btn.setText(_translate("MainWindow", "UP"))
        self.down_rcr_btn.setText(_translate("MainWindow", "DOWN"))
        self.clear_rcr_txt_btn.setText(_translate("MainWindow", "Clear"))
        self.stop_rcr_btn.setStatusTip(_translate("MainWindow", "emergency STOP!!!!"))
        self.stop_rcr_btn.setText(_translate("MainWindow", "STOP"))
        self.speed_rcr_lineEdit.setText(_translate("MainWindow", "0"))
        self.speed_rcr_lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.height_set_rcr_lineEdit.setText(_translate("MainWindow", "0"))
        self.height_set_rcr_lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.rcr_ab_height_label.setText(_translate("MainWindow", "H"))
        self.rcr_ab_vel_label.setText(_translate("MainWindow", "V"))
        self.height_rcr_lineEdit.setText(_translate("MainWindow", "0"))
        self.height_rcr_lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.vel_set_rcr_lineEdit.setText(_translate("MainWindow", "0"))
        self.vel_set_rcr_lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.rcr_speed_label.setText(_translate("MainWindow", "Speed"))
        self.rcr_height_label.setText(_translate("MainWindow", "Height"))
        self.rcr_ab_vel_label_2.setText(_translate("MainWindow", "mm/s"))
        self.rcr_ab_height_label_2.setText(_translate("MainWindow", "mm"))
        self.motor_arduino_ctr_label.setText(_translate("MainWindow", "Controller Arduino:"))
        self.detect_control_com_btn.setText(_translate("MainWindow", "detect"))
        self.open_control_com_btn.setText(_translate("MainWindow", "open"))
        self.close_control_com_btn.setText(_translate("MainWindow", "close"))
        self.rcrnode_open_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>open ros publish, should be pressed with two COMs open</p></body></html>"))
        self.rcrnode_open_btn.setText(_translate("MainWindow", "rosnode open"))
        self.icon_cuhk_label.setStatusTip(_translate("MainWindow", "http://www.cuhk.edu.com, Welcome to SGL github: https://github.com/Luminary-S"))
        self.icon_cuhk_label.setText(_translate("MainWindow", "CUHK"))
        self.icon_curi_label.setStatusTip(_translate("MainWindow", "http://ri.cuhk.edu.hk/, Welcome to SGL github: https://github.com/Luminary-S"))
        self.icon_curi_label.setText(_translate("MainWindow", "CURI"))
        self.real_time_info_label.setText(_translate("MainWindow", "Realtime INFO"))
        self.clear_real_time_txt_btn.setText(_translate("MainWindow", "Clear real time INFO"))
        self.sensor_info_gBox.setTitle(_translate("MainWindow", "  Sensor INFO"))
        self.clear_sensor_txt_btn.setText(_translate("MainWindow", "Clear"))
        self.sensor_N_lab.setText(_translate("MainWindow", "N"))
        self.sensor_force_label.setText(_translate("MainWindow", "Force"))
        self.sensor_sonic_label.setText(_translate("MainWindow", "Ultra sonic( base to window)"))
        self.sensor_cm_label.setText(_translate("MainWindow", "cm"))
        self.detect_sensor_com_btn.setText(_translate("MainWindow", "detect"))
        self.open_sensor_com_btn.setText(_translate("MainWindow", "open"))
        self.close_sensor_com_btn.setText(_translate("MainWindow", "close"))
        self.groupBox.setTitle(_translate("MainWindow", "UR INFO"))
        self.adjust_UR_EE_pos_gBox.setTitle(_translate("MainWindow", "UR EE Pos step movement"))
        self.ur_forward_btn.setText(_translate("MainWindow", "⦿"))
        self.ur_left_btn.setText(_translate("MainWindow", "⇦"))
        self.ur_up_btn.setText(_translate("MainWindow", "⇧"))
        self.ur_back_btn.setText(_translate("MainWindow", "◯"))
        self.ur_right_btn.setText(_translate("MainWindow", "⇨"))
        self.ur_down_btn.setText(_translate("MainWindow", "⇩"))
        self.adjust_UR_EE_atti_gBox.setTitle(_translate("MainWindow", "UR EE Attitude step movement"))
        self.ur_ee_roll1_btn.setToolTip(_translate("MainWindow", "pitch"))
        self.ur_ee_roll1_btn.setText(_translate("MainWindow", "↻"))
        self.ur_ee_pitch1_btn.setText(_translate("MainWindow", "⤸"))
        self.ur_ee_roll2_btn.setText(_translate("MainWindow", "↺"))
        self.ur_ee_yaw1_btn.setText(_translate("MainWindow", "↩"))
        self.ur_ee_pitch2_btn.setText(_translate("MainWindow", "⤹"))
        self.ur_ee_yaw2_btn.setText(_translate("MainWindow", "↪"))
        self.get_init_ur_pos_btn.setText(_translate("MainWindow", "GET INIT Joint Angles"))
        self.get_final_ur_pos_btn.setText(_translate("MainWindow", "GET Final Joint Angles"))
        self.clear_ur_info_txt_btn.setText(_translate("MainWindow", "Clear UR INFO"))
        self.ur_choose_box.setItemText(0, _translate("MainWindow", "ur3"))
        self.ur_choose_box.setItemText(1, _translate("MainWindow", "ur5"))
        self.ur_choose_ok_btn.setText(_translate("MainWindow", "OK"))
        self.ur_launch_btn.setText(_translate("MainWindow", "Launch"))
        self.ur_close_launch_btn.setText(_translate("MainWindow", "Close Launch"))
        self.ur_core_btn.setText(_translate("MainWindow", "Core"))
        self.ur_close_core_btn.setText(_translate("MainWindow", "Close Core"))


